### ISSUE TITLE
3.2.3: does not activate when media player controls are enabled and audacious is running

### ISSUE THREAD

**Issue by morph027** [linuxmint/cinnamon-screensaver#159]
I'm using audacious for playing music ... sound applet integrates fine. But the screensaver does not work anymore when enabling media player controls. In fact, nothing happens but the process consumes a lot of CPU until i kill it. I'm using the packages from embrosyn's PPA, but the same happens when i build the package on my own.

```bash
# uname -a
Linux morph 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```bash
(cinnamon-screensaver-main.py:10371): Gtk-WARNING **: Error loading image 'file:///usr/share/themes/Mint-Y-Darker/gtk-3.0/assets/thumbnail-frame.png': Error opening file: No such file or directory
/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py:75: Warning: g_base64_encode_step: assertion 'in != NULL' failed
  css = provider.to_string()
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
Starting screensaver...
Successfully using logind
```

**Comment by morph027** [comment]
VLC works flawlessly...

**Comment by clefebvre** [comment]
I removed position tracking. I don't know if this is related but it's worth re-testing: https://github.com/linuxmint/cinnamon-screensaver/commit/d332cfd20bb756e0a3b2fdfb982ad339da9bb187

**Comment by morph027** [comment]
Right now:

```
morph@test:~$ cinnamon-screensaver --debug
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 17, in <module>
    from service import ScreensaverService
  File "/usr/share/cinnamon-screensaver/service.py", line 9, in <module>
    from manager import ScreensaverManager
  File "/usr/share/cinnamon-screensaver/manager.py", line 10, in <module>
    from stage import Stage
  File "/usr/share/cinnamon-screensaver/stage.py", line 13, in <module>
    from audioPanel import AudioPanel
  File "/usr/share/cinnamon-screensaver/audioPanel.py", line 7, in <module>
    from playerControl import PlayerControl
  File "/usr/share/cinnamon-screensaver/playerControl.py", line 11, in <module>
    from widgets.blinkingLabel import BlinkingLabel
ImportError: No module named 'widgets.blinkingLabel'
```

Do i need to re-build another package too?

**Comment by morph027** [comment]
Ok, compiled the whole bunch of packages and now it works. Thank you!
