### ISSUE TITLE
Cannot unlock screen in 3.2.8

### ISSUE THREAD

**Issue by dpiotrowski** [linuxmint/cinnamon-screensaver#169]
Hi
Since updating cinnamon-screensaver to version 3.2.8 I'm having issues with unlocking the screen. The issue is that when I try to unlock the screen and type my password it doesn't react to hitting Enter or clicking the 'Unlock' icon. To get back to the desktop I need to resort to clicking the 'Switch user' icon and type my password there.

What I've noticed is that every time I try to unlock the screen a new process is spawned that is eating up lots of CPU: `/usr/share/cinnamon-screensaver/pamhelper/cinnamon-screensaver-pam-helper`. I've tried stracing the process and got an endless loop of this:
```
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=10, events=0}], 4, 0) = 0 (Timeout)
recvmsg(6, 0x7ffea60d7460, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=10, events=0}], 4, 0) = 0 (Timeout)
recvmsg(6, 0x7ffea60d7460, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=10, events=0}], 4, 0) = 0 (Timeout)
recvmsg(6, 0x7ffea60d7460, 0)           = -1 EAGAIN (Resource temporarily unavailable)
```

I've also tried the following:

1. killed cinnamon-screensaver
2. run `cinnamon-screensaver --debug` in the terminal
3. locked the screen and tried to unlock it by typing the password and hitting Enter and by clicking the 'unlock' icon
4. having failed the above I resorted to the 'Another user' method

The output from `cinnamon-screensaver --debug` is as follows:

```
erathiel@e31:~» cinnamon-screensaver --debug

(cinnamon-screensaver-main.py:2747): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:63:17: Theming engine 'unico' not found

(cinnamon-screensaver-main.py:2747): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:63:17: Theming engine 'unico' not found
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
Starting screensaver...
Successfully using logind

couldn't grab keyboard

(cinnamon-screensaver-pam-helper:2758): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:63:17: Theming engine 'unico' not found
pam_start ("cinnamon-screensaver", "erathiel", ...) ==> 0 (Success)

(cinnamon-screensaver-main.py:2747): Gtk-WARNING **: Symbolic icon screensaver-unlock-symbolic-ltr of size 16 is in an icon theme directory of size 128

(cinnamon-screensaver-main.py:2747): Gtk-WARNING **: Symbolic icon screensaver-switch-users-symbolic-ltr of size 16 is in an icon theme directory of size 128
Handling message style 1: 'Password: '
Waiting for respose to message style 1: 'Password: '
Waiting for lock
Waiting for response
Got message style 1: 'Password: '
Output from pam helper: 'CS_PAM_AUTH_SET_PROMPT_Password: _'
Output from pam helper: 'CS_PAM_AUTH_BUSY_FALSE'
Output from pam helper: ''
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/unlock.py", line 297, in on_auth_enter_key
    self.on_unlock_clicked()
  File "/usr/share/cinnamon-screensaver/unlock.py", line 290, in on_unlock_clicked
    self.auth_client.message_to_child(text)
  File "/usr/share/cinnamon-screensaver/pamhelper/authClient.py", line 101, in message_to_child
    b = GLib.Bytes(string.encode())
TypeError: boxed cannot be created directly; try using a constructor, see: help(GLib.Bytes)
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/unlock.py", line 290, in on_unlock_clicked
    self.auth_client.message_to_child(text)
  File "/usr/share/cinnamon-screensaver/pamhelper/authClient.py", line 101, in message_to_child
    b = GLib.Bytes(string.encode())
TypeError: boxed cannot be created directly; try using a constructor, see: help(GLib.Bytes)
Found no MDM server, ordering a new one
Locking cinnamon-screensaver

^C
erathiel@e31:~» ps aux | grep screensaver
erathiel    2846  0.0  0.0  13984   988 pts/0    S+   12:27   0:00 grep --color screensaver
```

I've checked for the `cinnamon-screensaver-pam-helper` process but obviously it was killed by SIGKILL-ing the main `cinnamon-screensaver` process.

Expected behaviour: typing the correct password and hitting Enter or clicking the 'Unlock' icon unlocks the screen and shows the desktop.

**Comment by mtwebster** [comment]
What distro/release?

**Comment by dpiotrowski** [comment]
Oh, sorry, I forgot to mention that. I'm running LMDE2 'Betsy'.

**Comment by mtwebster** [comment]
Fixed by 094594684ad6e6f820918430

**Comment by clefebvre** [comment]
update on its way (3.2.9)

**Comment by dpiotrowski** [comment]
Great news! I'm waiting for it to show up in the repos and will post an update here.

**Comment by dpiotrowski** [comment]
Obviously there was no real need to wait for the package as I could simply paste the modified content into the relevant file. It works perfectly. Thank you!
