### ISSUE TITLE
Password prompt missing while unlocking screen

### ISSUE THREAD

**Issue by dpiotrowski** [linuxmint/cinnamon-screensaver#190]
Hi
After updating from 3.2.9 to 3.2.12 on LMDE2, cinnamon-screensaver I'm having issues with unlocking the screen. When I try to unlock the screen, the password prompt doesn't appear for some time. In order to unlock the screen I need to do a considerable amount of random key pressing, though the amount of pressing does not seem to be consistent across attempts.

When I tried killing cinnamon-screensaver and running it with `--debug` the output I got was (first attempt with a faux password, the second with the correct one):

```
$ cinnamon-screensaver --debug

(cinnamon-screensaver-main.py:23182): Gtk-WARNING **: Symbolic icon screensaver-switch-users-symbolic-ltr of size 16 is in an icon theme directory of size 128
pam_start ("cinnamon-screensaver", "erathiel", ...) ==> 0 (Success)
Handling message style 1: 'Password: '
Waiting for respose to message style 1: 'Password: '
Waiting for lock
Waiting for response
Got message style 1: 'Password: '
Output from pam helper: 'CS_PAM_AUTH_SET_PROMPT_Password: _'
Output from pam helper: 'CS_PAM_AUTH_BUSY_FALSE'
Output from pam helper: ''
auth_message_handler processing response string: 'REDACTED'
should interrupt: 0
Got response
Got respose to message style 1: interrupt:0
Msg handler returned 1
Output from pam helper: 'CS_PAM_AUTH_BUSY_TRUE'
Output from pam helper: ''

(cinnamon-screensaver-main.py:23182): Gtk-WARNING **: Symbolic icon screensaver-unlock-symbolic-ltr of size 16 is in an icon theme directory of size 128

(cinnamon-screensaver-main.py:23182): Gtk-WARNING **: Symbolic icon screensaver-switch-users-symbolic-ltr of size 16 is in an icon theme directory of size 128
   pam_authenticate (...) ==> 7 (Authentication failure)

(cinnamon-screensaver-pam-helper:23196): GLib-CRITICAL **: Source ID 11 was not found when attempting to remove it
 pam_end (...) ==> 0 (Success)
Verify user returned: FALSE
Verify user returned error: Incorrect password.
Authentication failed, retrying (1)
Output from pam helper: 'CS_PAM_AUTH_FAILURE'
Output from pam helper: ''
pam_start ("cinnamon-screensaver", "erathiel", ...) ==> 0 (Success)
Handling message style 1: 'Password: '
Waiting for respose to message style 1: 'Password: '
Waiting for lock
Waiting for response
Got message style 1: 'Password: '
Output from pam helper: 'CS_PAM_AUTH_SET_PROMPT_Password: _'
Output from pam helper: 'CS_PAM_AUTH_BUSY_FALSE'
Output from pam helper: ''
auth_message_handler processing response string: 'REDACTED'
should interrupt: 0
Got response
Got respose to message style 1: interrupt:0
Msg handler returned 1
Output from pam helper: 'CS_PAM_AUTH_BUSY_TRUE'
Output from pam helper: ''
   pam_authenticate (...) ==> 0 (Success)
pam_acct_mgmt (...) ==> 0 (Success)
   pam_setcred (...) ==> 0 (Success)
```

Additional quirk in case you overlooked it: --debug now prints the actual password you type in at the login prompt. Is it supposed to do that? Last time I checked (version 3.2.8) it didn't print any such thing.

Expected behaviour: when the screen is locked pressing a button or moving the mouse should bring the password prompt immediately.

**Comment by mtwebster** [comment]
I'll check on this on my LMDE machine today.  I did add additional logging at one point, including what travels thru the pipe.  I'll put a big warning at the start of logging to warn the user in this mode so they can redact.

**Comment by Wini-Buh** [comment]
I have exactly the same problem here (also LMDE2 on two different PCs). With version 3.2.9 it worked like expected, after the update to 3.2.12 it is not possible to unlock the screen (in a normal way).

**Comment by michael7890** [comment]
Same here on LMDE2 with version 3.2.12. Oddly enough, when I first upgraded to screensaver 3.2.12 (which came with Cinnamon version 3.2.7), no locking occurred at all. This was after just restarting the new Cinnamon.

Then I did a reboot. Now, the first time the screensaver is started, I do get both a locked screen AND the log in prompt. Start the screensaver again, though, the screen does lock, but there is no login prompt, and I'v only been able to resolve this by restarting via Ctrl+Alt+Backspace.

**Comment by rwpreece** [comment]
Same issues here after 12/22/2016 updates to the following packages:
libcscreensaver0 from 3.2.9+betsy to 3.2.12+betsy
cinnamon from 3.2.6+betsy to 3.2.7+betsy
cinnamon-common from 3.2.6+betsy to 3.2.7+betsy 
cinnamon-screensaver from 3.2.9+betsy to 3.2.12+betsy

**Comment by mtwebster** [comment]
Should be fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/0cf592af37f65229157712d40123b5931ff9a164 - just waiting on a new release, coming asap.

If you don't want to wait, you can edit the installed file (`sudo gedit /usr/share/cinnamon-screensaver/manager.py`) and move the line in that commit yourself (just restart the screensaver or log out/in.)

**Comment by dpiotrowski** [comment]
@mtwebster I've edited the file manually, restarted cinnamon-screensaver and tested. It seems to work OK :) Thank you!

**Comment by rwpreece** [comment]
Thanks Michael.  Works great. :D

**Comment by chirag7jain** [comment]
I think the fix is already in but the issue still persists

**Comment by renarena** [comment]
> I checked the code, the fix is included but the issue still persist
I too (in LMDE)

**Comment by mtwebster** [comment]
Reiterating what was just said, make sure you log out/in or kill and restart the screensaver.

**Comment by Efpophis** [comment]
I'm seeing this behavior today after a full power down restart. Mint 18.3. Didn't start until the kernel update that came out yesterday, if that helps anything.

**Comment by MingcongBai** [comment]
Still reproducible here on AOSC OS, version 3.6.2.

**Comment by ipaqmaster** [comment]
Experiencing this on an up to date Arch machine today with (kernel 5.19.3)

```
$ cinnamon-screensaver-command -l
Traceback (most recent call last):
  File "/usr/bin/cinnamon-screensaver-command", line 98, in _on_proxy_ready
    self.perform_action()
  File "/usr/bin/cinnamon-screensaver-command", line 115, in perform_action
    self.proxy.call_lock_sync(self.message)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method Lock is not implemented on interface org.cinnamon.ScreenSaver (19)
```

Various other online solutions regarding subprocess.run.pth don't seem to resolve it.
