### ISSUE TITLE
Can't get screensaver 3.2.12 to work on Manjaro (Archlinux)

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/cinnamon-screensaver#193]

**Comment by oberon2007** [comment]
Sorry, I submitted the unfinished issue 😉 
Yesterday I build all the latest cinnamon packages on Manjaro. The screensaver however doesn't work.
I noticed that on Debian you are packaging the pam-helper separately now so i suspect there may be my problem.
Currently I just build one screensaver package with make, make install and I see that pam helper still does get installed to **/usr/lib/cinnamon-screensaver/**
Am I missing anything here?

**Comment by oberon2007** [comment]
```
$ cinnamon-screensaver-command -l
Can't connect to screensaver!
```
```
$ cinnamon-screensaver
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
Starting screensaver...
Not running under the session scope, trying XDG_SESSION_ID
found session: c2
Successfully using logind
```
Now I'm able to lock the screen with ``cinnamon-screensaver-command -l`` but it will not unlock when I enter the password:
```
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/unlock.py", line 232, in on_auth_enter_key
    self.on_unlock_clicked()
  File "/usr/share/cinnamon-screensaver/unlock.py", line 223, in on_unlock_clicked
    self.authenticate(text)
  File "/usr/share/cinnamon-screensaver/unlock.py", line 256, in authenticate
    CinnamonDesktop.desktop_check_user_password(self.user_name,
  File "/usr/lib/python3.5/site-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.CinnamonDesktop' object has no attribute 'desktop_check_user_password'
```

**Comment by leigh123linux** [comment]
This is your mess, **desktop_check_user_password** was removed from cinnamon-screensaver-3.2.7 so this error can't exist in 3.2.12

https://github.com/linuxmint/cinnamon-screensaver/commit/38a626d1a3c64736f0acfe22b39aaefbf1c206f4

Make sure you have installed cinnamon-desktop-3.2.2+ as cinnamon-screensaver-3.2.7+ requires it

**Comment by oberon2007** [comment]
Thank you for your answer. My bad of course about the error I posted, sorry. That was in fact after I had downgrading to **cinnamon-screensaver 3.2.2** again... **cinnamon-desktop 3.2.4** is installed.
But, now with 3.2.12 again, first I found out that I needed a new dependency **python-setproctitle**. Now with that installed I get ``Critical error: PAM Helper cound not be found!`` even though the file **/usr/lib/cinnamon-screensaver/cinnamon-screensaver-pam-helper** is present aswell as
```
/etc/pam.d/cinnamon-screensaver
/usr/lib/cinnamon-screensaver/cinnamon-screensaver-pam-helper
/usr/share/cinnamon-screensaver/pamhelper/__pycache__/authClient.cpython-35.opt-1.pyc
/usr/share/cinnamon-screensaver/pamhelper/__pycache__/authClient.cpython-35.pyc
/usr/share/cinnamon-screensaver/pamhelper/authClient.py
```
Am I still missing anything?

**Comment by oberon2007** [comment]
After the helper error I get tons of errors like this - I suppose with every key action - probably a secondary problem because pam-helper can't be found:
```
(cinnamon-screensaver-main.py:12571): GLib-GIO-CRITICAL **: g_subprocess_newv: assertion 'argv != NULL && argv[0] != NULL && argv[0][0] != '\0'' failed
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/stage.py", line 589, in do_motion_notify_event
    return self.event_handler.on_motion_event(event)
  File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 51, in on_motion_event
    self.on_user_activity()
  File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 32, in on_user_activity
    self.manager.simulate_user_activity()
  File "/usr/share/cinnamon-screensaver/manager.py", line 148, in simulate_user_activity
    if status.Locked and self.stage.initialize_pam():
  File "/usr/share/cinnamon-screensaver/stage.py", line 456, in initialize_pam
    return self.unlock_dialog.initialize_auth_client()
  File "/usr/share/cinnamon-screensaver/unlock.py", line 165, in initialize_auth_client
    return self.auth_client.initialize()
  File "/usr/share/cinnamon-screensaver/pamhelper/authClient.py", line 66, in initialize
    Gio.SubprocessFlags.STDOUT_PIPE)
TypeError: constructor returned NULL
```

**Comment by oberon2007** [comment]
I got I now. cinnamon-screensaver-pam-helper is actually placed in the wrong path. It's not supposed to end up in subdir /usr/lib/cinnamon-screensaver/cinnamon-screensaver-pam-helper but in /usr/lib directly
```
try:
            helper_path = None
            architecture = platform.machine()
            paths = ["/usr/lib"]

            # On x86 archs, iterate through multiple paths
            # For instance, on a Mint i686 box, the path is actually /usr/lib/i386-linux-gnu
            x86archs = ["i386", "i486", "i586", "i686"]
            if architecture in x86archs:
                for arch in x86archs:
                    paths += ["/usr/lib/%s" % arch, "/usr/lib/%s-linux-gnu" % arch]
            elif architecture == "x86_64":
                paths += ["/usr/lib/x86_64", "/usr/lib/x86_64-linux-gnu", "/usr/lib64"]
            else:
                paths += ["/usr/lib/%s" % architecture, "/usr/lib/%s-linux-gnu" % architecture]

            for path in paths:
                full_path = os.path.join(path, "cinnamon-screensaver-pam-helper")
                if os.path.exists(full_path):
                    helper_path = full_path
                    break

            if helper_path is None:
                print ("Critical error: PAM Helper cound not be found!")
```

**Comment by oberon2007** [comment]
When I move the file manually there, everything works.

**Comment by leigh123linux** [comment]
You need this commit as you have used a sub-directory for cinnamon-screensaver-pam-helper

https://github.com/linuxmint/cinnamon-screensaver/commit/82616b6bd19890797130d09be303b6bd23401ad8

**Comment by oberon2007** [comment]
Great! Thank you.
