### ISSUE TITLE
No unlock_dialog because of failure in PlaybackStatus

### ISSUE THREAD

**Issue by jeromekelleher** [linuxmint/cinnamon-screensaver#196]
After upgrading to Linux Mint 18.1, I am unable to unlock my screen (except by killing cinnamon-screensaver). Please see below the trace when I run this in a shell. I'm happy to help debugging this if you need any more details (although might not have access to this particular computer for a few days).

```
$ cinnamon-screensaver
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
Starting screensaver...
Successfully using logind
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/stage.py", line 169, in on_realized
    self.setup_children()
  File "/usr/share/cinnamon-screensaver/stage.py", line 186, in setup_children
    self.setup_albumart()
  File "/usr/share/cinnamon-screensaver/stage.py", line 333, in setup_albumart
    self.albumart_widget = AlbumArt(self.screen, self.away_message, utils.get_mouse_monitor())
  File "/usr/share/cinnamon-screensaver/albumArt.py", line 33, in __init__
    self.player = self.watcher.get_best_player()
  File "/usr/share/cinnamon-screensaver/dbusdepot/mediaPlayerWatcher.py", line 260, in get_best_player
    if client.get_playback_status() == PlaybackStatus.Playing:
  File "/usr/share/cinnamon-screensaver/dbusdepot/mediaPlayerWatcher.py", line 58, in get_playback_status
    status = PlaybackStatus(eval("PlaybackStatus." + str_prop))
  File "<string>", line 1
    PlaybackStatus.
                  ^
SyntaxError: unexpected EOF while parsing
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/stage.py", line 612, in do_key_press_event
    return self.event_handler.on_key_press_event(event)
  File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 77, in on_key_press_event
    self.manager.queue_dialog_key_event(event)
  File "/usr/share/cinnamon-screensaver/manager.py", line 289, in queue_dialog_key_event
    self.stage.queue_dialog_key_event(event)
  File "/usr/share/cinnamon-screensaver/stage.py", line 402, in queue_dialog_key_event
    self.unlock_dialog.queue_key_event(event)
AttributeError: 'NoneType' object has no attribute 'queue_key_event'
```

**Comment by jeromekelleher** [comment]
Thanks for the fix. For others that may hit this issue, it seems that this is caused by spotify. If spotify is running, the playback status is malformed and triggers the issue. If spotify is not running, there are no problems.
