### ISSUE TITLE
Namespace XApp not available

### ISSUE THREAD

**Issue by lehitoskin** [linuxmint/cinnamon-screensaver#206]
For the past while I've been getting this error:
```
~> cinnamon-screensaver
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 18, in <module>
    from service import ScreensaverService
  File "/usr/share/cinnamon-screensaver/service.py", line 9, in <module>
    from manager import ScreensaverManager
  File "/usr/share/cinnamon-screensaver/manager.py", line 10, in <module>
    from stage import Stage
  File "/usr/share/cinnamon-screensaver/stage.py", line 8, in <module>
    import singletons
  File "/usr/share/cinnamon-screensaver/singletons.py", line 46, in <module>
    gi.require_version('XApp', '1.0')
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace XApp not available
```

I've made certain that xapps is installed, but nothing has changed. I'm using cinnamon-screensaver version 3.2.13

**Comment by leigh123linux** [comment]
Do you have the typelib installed (gir1.2-xapp-1.0)?

```
$ rpm -ql xapps |grep type
/usr/lib64/girepository-1.0/XApp-1.0.typelib
```

**Comment by lehitoskin** [comment]
Ah! That was it. I needed to compiled XApps with introspection enabled. Thanks!
