### ISSUE TITLE
Screensaver/lock-screen N/A

### ISSUE THREAD

**Issue by Raptus1** [linuxmint/cinnamon-screensaver#230]
I'm having issues with the screensaver or lockscreen not working on two different computers both on 17.04 using ppa:embrosyn/cinnamon repository (and previous gwendal nightly that I removed to check if that was the cause).

When I run cinnamon-screensaver --debug I get the following using the embrosyn repo:

> Unable to init server: Could not connect: Connection refused
> Unable to init server: Could not connect: Connection refused
> Traceback (most recent call last):
>   File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 120, in <module>
>     main = Main()
>   File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 57, in __init__
>     from service import ScreensaverService
>   File "/usr/share/cinnamon-screensaver/service.py", line 9, in <module>
>     from manager import ScreensaverManager
>   File "/usr/share/cinnamon-screensaver/manager.py", line 10, in <module>
>     from stage import Stage
>   File "/usr/share/cinnamon-screensaver/stage.py", line 11, in <module>
>     import singletons
>   File "/usr/share/cinnamon-screensaver/singletons.py", line 33, in <module>
>     NotificationWatcher = CScreensaver.NotificationWatcher.new(status.Debug)
> TypeError: CScreensaver.NotificationWatcher.new() takes exactly 0 arguments (1 given)

and this on the other computer using gwendal nightly repo:

> 
> Debug mode active
> Cinnamon Screensaver support not found in current theme - adding some...
> Traceback (most recent call last):
>   File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 120, in <module>
>     main = Main()
>   File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 64, in __init__
>     self.do_style_overrides()
>   File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 113, in do_style_overrides
>     if fallback_prov.load_from_data(fallback_css.encode()):
> GLib.Error: gtk-css-provider-error-quark: <data>:63:14'max-height' is not a valid property name (3)

is this even relevant? I'm new looking to join in.

**Comment by Raptus1** [comment]
Found that there was som pagages that had not been updated on the stable version. After this all was good with the loc-screen. Will start using this repo on both computers.
