### ISSUE TITLE
screen-saver not starting after resume, when pressing ctrl-alt-l or running directly

### ISSUE THREAD

**Issue by neuronotic** [linuxmint/cinnamon-screensaver#245]
```
 * Cinnamon-Screensaver version 3.4.2
 * Distribution - Ubuntu 17.04
 * Graphics hardware *and* driver used - Lenovo T460s using i915 driver
 * 32 or 64 bit - cinnamon-screensaver:all/zesty 3.4.2-1~zesty0 uptodate
 ```

**Issue**

Screen-saver (locked) does not come on when resuming from suspending or when hitting ctrl-alt-l or when running from terminal.

**Steps to reproduce**

Any of:
- resume from suspend
- attempting to lock screen (ctrl-alt-l)
- executing `cinnamon-screensaver`

**Expected behaviour**

screen-saver to start with locked screen

**Other information**

executing ```cinnamon-screensaver --debug``` yields:

```Debug mode active
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 120, in <module>
    main = Main()
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 57, in __init__
    from service import ScreensaverService
  File "/usr/share/cinnamon-screensaver/service.py", line 9, in <module>
    from manager import ScreensaverManager
  File "/usr/share/cinnamon-screensaver/manager.py", line 10, in <module>
    from stage import Stage
  File "/usr/share/cinnamon-screensaver/stage.py", line 11, in <module>
    import singletons
  File "/usr/share/cinnamon-screensaver/singletons.py", line 33, in <module>
    NotificationWatcher = CScreensaver.NotificationWatcher.new(status.Debug)
TypeError: CScreensaver.NotificationWatcher.new() takes exactly 0 arguments (1 given)
```

Seems different to issue #242 as when resuming from suspension, does not appear to run screen saver at all.

**Comment by mtwebster** [comment]
You seem to have some package version mismatch - where are you getting the packages from? A ppa?

The last line tells me your libcscreensaver0 package is too old or not the same level as cinnamon-screensaver itself.

**Comment by neuronotic** [comment]
I've got embrosyn in my sources list. Looks like dealing with the version fixed it.

I had this:
```
daz@lapetus:~$ dpkg --list | grep screensaver
ii  cinnamon-screensaver                                             3.4.2-1~zesty0                                all          Cinnamon screen saver and locker
ii  cinnamon-screensaver-pam-helper                                  3.4.2-1~zesty0                                amd64        PAM helper for cinnamon-screensaver
ii  cinnamon-screensaver-x-plugin                                    3.2.13-3                                      all          XScreensaver plugin for cinnamon-screensaver
rc  gnome-screensaver                                                3.6.1-7ubuntu5                                amd64        GNOME screen saver and locker
ii  libcscreensaver0:amd64                                           3.2.13-3                                      amd64        library and introspection data used by cinnamon-screensaver
ii  xscreensaver-data                                                5.36-1ubuntu1                                 amd64        Screen saver modules for screensaver frontends
ii  xscreensaver-data-extra                                          5.36-1ubuntu1                                 amd64        Extra screen saver modules for screensaver frontends
ii  xscreensaver-gl                                                  5.36-1ubuntu1                                 amd64        GL(Mesa) screen saver modules for screensaver frontends
ii  xscreensaver-gl-extra                                            5.36-1ubuntu1                                 amd64        Extra GL(Mesa) screen saver modules for screensaver frontends
```

upgraded so now I have this:
```daz@lapetus:/etc/apt$ dpkg --list | grep screensaver
ii  cinnamon-screensaver                                             3.4.2-1~zesty0                                all          Cinnamon screen saver and locker
ii  cinnamon-screensaver-pam-helper                                  3.4.2-1~zesty0                                amd64        PAM helper for cinnamon-screensaver
ii  cinnamon-screensaver-x-plugin                                    3.4.2-1~zesty0                                all          XScreensaver plugin for cinnamon-screensaver
rc  gnome-screensaver                                                3.6.1-7ubuntu5                                amd64        GNOME screen saver and locker
ii  libcscreensaver0:amd64                                           3.4.2-1~zesty0                                amd64        library and introspection data used only by cinnamon-screensaver
ii  xscreensaver-data                                                5.36-1ubuntu1                                 amd64        Screen saver modules for screensaver frontends
ii  xscreensaver-data-extra                                          5.36-1ubuntu1                                 amd64        Extra screen saver modules for screensaver frontends
ii  xscreensaver-gl                                                  5.36-1ubuntu1                                 amd64        GL(Mesa) screen saver modules for screensaver frontends
ii  xscreensaver-gl-extra                                            5.36-1ubuntu1                                 amd64        Extra GL(Mesa) screen saver modules for screensaver frontends
```
And now when I execute ```cinnamon-screensaver``` I get:
````
daz@lapetus:/etc/apt$ cinnamon-screensaver --debug
Debug mode active
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
Starting screensaver...
Not running under the session scope, trying XDG_SESSION_ID
found session: c16
Successfully using logind
```
which then allows me to lock screen, etc. 

success.
