### ISSUE TITLE
Black screen after woke up from suspend.

### ISSUE THREAD

**Issue by kruzo7** [linuxmint/cinnamon-screensaver#343]
```
 * cinnamon-screensaver 4.6.0+ulyana
 * Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
 * Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Lenovo driver: i915 
           v: kernel bus ID: 00:02.0 chip ID: 8086:0116 
           Device-2: NVIDIA GF108M [GeForce GT 555M] vendor: Lenovo driver: nvidia v: 390.138 bus ID: 01:00.0 
           chip ID: 10de:0deb 
           Display: x11 server: X.Org 1.20.8 driver: modesetting,nvidia unloaded: fbdev,nouveau,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce GT 555M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.138 direct render: Yes 
 * 64 bit
 * laptop
 * extra hdmi monitor
 * system updated
 ```
dump: [cinnamon-screen.txt](https://github.com/linuxmint/cinnamon-screensaver/files/4946217/cinnamon-screen.txt)
inxi info: [info_inxi.txt](https://github.com/linuxmint/cinnamon-screensaver/files/4946222/info_inxi.txt)

**Issue**
Black screen after woke up from suspend.

**Steps to reproduce**
- go to suspend mode
- wait to all monitors turn off
- press any key to woke up
- black screen show up

**Expected behaviour**
Display login screen instead black screen.

**Other information**
After woke up i can switch between tty* consoles.
Ctrl+Alt+F1 switch to tty1
Ctrl+Alt+F2 switch to tty2 - screen appear
Ctrl+Alt+F7 switch to tty7 - login screen appear
After login everything seems to work, except lock screen Ctrl+Alt+L

**Other information 2**
Adding nomodeset, nvidia_drm.modeset=0 pcie_aspm.policy=performance,  nvidia.modeset=0 and similar to GRUB_CMDLINE_LINUX and update-grub didn't help.

**Comment by leigh123linux** [comment]
The stack trace is useless without the debugging symbols, install libcscreensaver-dbg and post it again.

**Comment by kruzo7** [comment]
Strange but this error not appear any more. Problem still exists.
This is log with important messages (Mint Log app) from after woke up: 
[cinnamon-screen_2.txt](https://github.com/linuxmint/cinnamon-screensaver/files/4970848/cinnamon-screen_2.txt)

**Comment by kruzo7** [comment]
This log should contains some more info (with libcscreensaver-dbg)

[cinnamon-screen_3.txt](https://github.com/linuxmint/cinnamon-screensaver/files/5026814/cinnamon-screen_3.txt)

**Comment by kruzo7** [comment]
Crash from today:
[cinnamon-screen_5.txt](https://github.com/linuxmint/cinnamon-screensaver/files/5033819/cinnamon-screen_5.txt)

**Comment by kruzo7** [comment]
===================================================================
 Info                                                              
===================================================================
           PID: 7827 (cinnamon-screen)
           UID: 1000 ()
           GID: 1000 ()
        Signal: 11 (SEGV)
     Timestamp: Sun 2020-08-09 10:48:12 CEST (27min ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-screensaver/cinnamon-screensaver-pam-helper
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-screensaver/cinnamon-screensaver-pam-helper
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 ()
       Boot ID: 12e39f3cf5aa4e8980bdfe8d9f2918c3
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: waldek-Lenovo-IdeaPad-Y570
       Storage: /var/lib/systemd/coredump/core.cinnamon-screen.1000.12e39f3cf5aa4e8980bdfe8d9f2918c3.7827.1596962892000000000000.lz4
       Message: Process 7827 (cinnamon-screen) of user 1000 dumped core.
                
                Stack trace of thread 8064:
                #0  0x00007f8306a7fd5a __GI___strlen_sse2 (libc.so.6 + 0xb4d5a)
                #1  0x000055a64edd49eb stdin_monitor_task_thread (cinnamon-screensaver-pam-helper + 0x29eb)
                #2  0x00007f8306dfbc62 n/a (libgio-2.0.so.0 + 0xb5c62)
                #3  0x00007f8306c391d4 n/a (libglib-2.0.so.0 + 0x7c1d4)
                #4  0x00007f8306c38931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f8306732609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8306aed103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 8060:
                #0  0x00007f8306ae096f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f8306c0f1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f8306c0f533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f8306e64eda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007f8306c38931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f8306732609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8306aed103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 8059:
                #0  0x00007f8306ae096f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f8306c0f1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f8306c0f2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f8306c0f331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f8306c38931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f8306732609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f8306aed103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 7827:
                #0  0x00007f8306ae096f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f8306c0f1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f8306c0f533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f830717537d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #4  0x000055a64edd4729 main (cinnamon-screensaver-pam-helper + 0x2729)
                #5  0x00007f83069f20b3 __libc_start_main (libc.so.6 + 0x270b3)
                #6  0x000055a64edd481e _start (cinnamon-screensaver-pam-helper + 0x281e)
===================================================================
 GDB Log                                                           
===================================================================

warning: core file may not match specified executable file.
[New LWP 8064]
[New LWP 8060]
[New LWP 8059]
[New LWP 7827]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-screensaver/cinnamon-screensaver-pam-helper'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120	../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
[Current thread is 1 (Thread 0x7f82ff7fe700 (LWP 8064))]

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: core file may not match specified executable file.
[New LWP 8064]
[New LWP 8060]
[New LWP 8059]
[New LWP 7827]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-screensaver/cinnamon-screensaver-pam-helper'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120	../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
[Current thread is 1 (Thread 0x7f82ff7fe700 (LWP 8064))]
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x000055a64edd49eb in stdin_monitor_task_thread (task=0x55a650062d40, source_object=<optimized out>, task_data=<optimized out>, cancellable=<optimized out>) at ../../src/pamhelper/cinnamon-screensaver-pam-helper.c:314
#2  0x00007f8306dfbc62 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x00007f8306c391d4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f8306c38931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f8306732609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f8306aed103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: core file may not match specified executable file.
[New LWP 8064]
[New LWP 8060]
[New LWP 8059]
[New LWP 7827]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-screensaver/cinnamon-screensaver-pam-helper'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120	../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
[Current thread is 1 (Thread 0x7f82ff7fe700 (LWP 8064))]

Thread 4 (Thread 0x7f83056a6300 (LWP 7827)):
#0  0x00007f8306ae096f in __GI___poll (fds=0x55a650155fe0, nfds=3, timeout=0) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 1
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f8306c0f1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f8306c0f533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f830717537d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#4  0x000055a64edd4729 in main (argc=<optimized out>, argv=<optimized out>) at ../../src/pamhelper/cinnamon-screensaver-pam-helper.c:503
        error = 0x0
        nolock_reason = 0x0

Thread 3 (Thread 0x7f8304dac700 (LWP 8059)):
#0  0x00007f8306ae096f in __GI___poll (fds=0x55a65004dec0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f8306c0f1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f8306c0f2e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f8306c0f331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f8306c38931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f8306732609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140200698889984, 2597553826083297015, 140724100494638, 140724100494639, 140724100494784, 140200698887232, -2663223027912222985, -2663226520456866057}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8306aed103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f82fffff700 (LWP 8060)):
#0  0x00007f8306ae096f in __GI___poll (fds=0x55a650061370, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f8306c0f1ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f8306c0f533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f8306e64eda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f8306c38931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f8306732609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140200617441024, 2597553826083297015, 140724100495070, 140724100495071, 140724100495216, 140200617438272, -2663418971299588361, -2663226520456866057}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8306aed103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f82ff7fe700 (LWP 8064)):
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
No locals.
#1  0x000055a64edd49eb in stdin_monitor_task_thread (task=0x55a650062d40, source_object=<optimized out>, task_data=<optimized out>, cancellable=<optimized out>) at ../../src/pamhelper/cinnamon-screensaver-pam-helper.c:314
        buf = "\004", '\000' <repeats 23 times>, "|\000\000\000w\000\000\000n\000\000\000_", '\000' <repeats 19 times>, "\260\004\002\000\000\000\000\000 \000\000\360\202\177\000\000\360\a\000\000\000\000\000\000P\v\000\360\202\177\000\000\000\000\000\000\000\000\000\000@\334\177\377\202\177\000\000'\000\000\000\000\000\000\000`\v\000\360\202\177\000\000\320b\371O\246U\000\000 \000\000\000\000\000\000\000\240\275\305\006\203\177\000\000'\000\000\000\000\000\000\000@D\316\006\203\177\000\000`\v\000\360\202\177\000\000\324\211\303\006\203\177\000\000\360\332\177\377\202\177\000\000\000\221\023P\246U\000\000\360\003\000\000\000\000\000\000"...
        input = 0x0
#2  0x00007f8306dfbc62 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#3  0x00007f8306c391d4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f8306c38931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f8306732609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140200609048320, 2597553826083297015, 140724100498862, 140724100498863, 140724100499008, 140200609045568, -2663417870177347849, -2663226520456866057}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8306aed103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x000055a64edd49eb in stdin_monitor_task_thread (task=0x55a650062d40, source_object=<optimized out>, task_data=<optimized out>, cancellable=<optimized out>) at ../../src/pamhelper/cinnamon-screensaver-pam-helper.c:314
#2  0x00007f8306dfbc62 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x00007f8306c391d4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f8306c38931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f8306732609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f8306aed103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
