### ISSUE TITLE
Cannot suspend laptop after upgrading to 5.0.2

### ISSUE THREAD

**Issue by warwickmm** [linuxmint/cinnamon-screensaver#377]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version): 5.0.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Arch
 * Graphics hardware *and* driver used:

00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
        Subsystem: Lenovo Device 225c
        Flags: bus master, fast devsel, latency 0, IRQ 138
        Memory at 2ffa000000 (64-bit, non-prefetchable) [size=16M]
        Memory at b0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at e000 [size=64]
        Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
        Capabilities: [40] Vendor Specific Information: Len=0c <?>
        Capabilities: [70] Express Root Complex Integrated Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [d0] Power Management version 2
        Capabilities: [100] Process Address Space ID (PASID)
        Capabilities: [200] Address Translation Service (ATS)
        Capabilities: [300] Page Request Interface (PRI)
        Kernel driver in use: i915
        Kernel modules: i915
 
* 32 or 64 bit: 64-bit
```

**Issue**

After upgrading the following packages, I can no longer suspend my laptop (Thinkpad X1 Carbon 6th generation):

* cinnamon 4.8.6 -> 5.0.2
* cinnamon-control-center 4.8.2 -> 5.0.1
* cinnamon-desktop 4.8.1 -> 5.0.0 
* cinnamon-screensaver 4.8.1 -> 5.0.2 
* cinnamon-session 4.8.0 -> 5.0.0 
* cinnamon-settings-daemon 4.8.5 -> 5.0.0 

I submitted this issue in this repository due to the cinnamon-screensaver warnings shown below:

**Steps to reproduce**

Close the lid (or use menu or hold down power button) to initiate suspend.  The resulting entries appear in the output of `journalctl -b`:
```
Jun 06 13:15:56 lenny systemd-logind[473]: Lid closed.
Jun 06 13:15:57 lenny dbus-daemon[990]: [session uid=1000 pid=990] Activating service name='org.cinnamon.ScreenSaver' requested by ':1.68' (uid=1000 pid=10324 comm="/usr/bin/python3 /usr/bin/cinnamon-screensaver-com")
Jun 06 13:15:57 lenny dbus-daemon[990]: [session uid=1000 pid=990] Successfully activated service 'org.cinnamon.ScreenSaver'
Jun 06 13:15:57 lenny cinnamon-session[983]: WARNING: t+1062.75944s: Detected that screensaver has appeared on the bus
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]: Traceback (most recent call last):
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 203, in spawn_stage
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.stage.activate(callback)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/stage.py", line 238, in activate
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     callback()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 323, in on_spawn_stage_complete
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.start_timers()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 376, in start_timers
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.start_lock_delay()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 418, in start_lock_delay
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.on_lock_delay_timeout()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 399, in on_lock_delay_timeout
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.set_locked(True)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 63, in set_locked
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.spawn_fallback_window()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 219, in spawn_fallback_window
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self._real_spawn_fallback_window(self)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 266, in _real_spawn_fallback_window
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.fb_pid = GLib.spawn_async(argv)[0]
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]: TypeError: gi._gi.spawn_async: first argument must be a sequence of strings
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]: Traceback (most recent call last):
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/service.py", line 75, in handle_lock
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     if self.manager.lock(msg):
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 78, in lock
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.set_locked(True)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 63, in set_locked
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.spawn_fallback_window()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 219, in spawn_fallback_window
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self._real_spawn_fallback_window(self)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 266, in _real_spawn_fallback_window
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.fb_pid = GLib.spawn_async(argv)[0]
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]: TypeError: gi._gi.spawn_async: first argument must be a sequence of strings
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]: Traceback (most recent call last):
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 463, in on_session_idle_changed
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.set_active(True)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 120, in set_active
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.stage.activate(self.on_spawn_stage_complete)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/stage.py", line 238, in activate
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     callback()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 323, in on_spawn_stage_complete
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.start_timers()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 376, in start_timers
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.start_lock_delay()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 418, in start_lock_delay
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.on_lock_delay_timeout()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 399, in on_lock_delay_timeout
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.set_locked(True)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 63, in set_locked
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.spawn_fallback_window()
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 219, in spawn_fallback_window
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self._real_spawn_fallback_window(self)
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:   File "/usr/share/cinnamon-screensaver/manager.py", line 266, in _real_spawn_fallback_window
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]:     self.fb_pid = GLib.spawn_async(argv)[0]
Jun 06 13:15:57 lenny org.cinnamon.ScreenSaver[10330]: TypeError: gi._gi.spawn_async: first argument must be a sequence of strings
```
After this, the laptop is _not_ suspended, but the lock screen is active.

Suspend/resume works without issues if I downgrade the back to the 4.8 versions listed above.

**Other information**

Output of `inxi -Fxxxzr`:
```
System:    Kernel: 5.12.9-arch1-1 x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: Cinnamon 4.8.6 tk: GTK 3.24.29 vt: 1 
           dm: LXDM Distro: Arch Linux 
Machine:   Type: Laptop System: LENOVO product: 20KG0022US v: ThinkPad X1 Carbon 6th serial: <filter> Chassis: type: 10 
           serial: <filter> 
           Mobo: LENOVO model: 20KG0022US v: SDK0J40709 WIN serial: <filter> UEFI-[Legacy]: LENOVO v: N23ET55W (1.30 ) 
           date: 08/31/2018 
Battery:   ID-1: BAT0 charge: 41.2 Wh (86.2%) condition: 47.8/57.0 Wh (83.9%) volts: 12.3 min: 11.6 model: LGC 01AV494 
           type: Li-poly serial: <filter> status: Discharging cycles: 379 
CPU:       Info: Quad Core model: Intel Core i7-8550U bits: 64 type: MT MCP arch: Kaby Lake note: check rev: A cache: 
           L2: 8 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 32012 
           Speed: 800 MHz min/max: 400/4000 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Lenovo driver: i915 v: kernel bus-ID: 00:02.0 chip-ID: 8086:5917 
           class-ID: 0300 
           Device-2: Acer Integrated Camera type: USB driver: uvcvideo bus-ID: 1-8:4 chip-ID: 5986:2115 class-ID: 0e02 
           Display: x11 server: X.org 1.20.11 driver: loaded: modesetting alternate: fbdev,intel,vesa 
           resolution: <missing: xdpyinfo> 
           Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Lenovo driver: snd_hda_intel v: kernel bus-ID: 00:1f.3 
           chip-ID: 8086:9d71 class-ID: 0403 
           Sound Server-1: ALSA v: k5.12.9-arch1-1 running: yes 
           Sound Server-2: JACK v: 0.125.0 running: no 
           Sound Server-3: PulseAudio v: 14.2 running: yes 
Network:   Device-1: Intel Ethernet I219-V vendor: Lenovo driver: e1000e v: kernel port: efa0 bus-ID: 00:1f.6 
           chip-ID: 8086:15d8 class-ID: 0200 
           IF: enp0s31f6 state: down mac: <filter> 
           Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: efa0 bus-ID: 02:00.0 chip-ID: 8086:24fd 
           class-ID: 0280 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 476.94 GiB used: 53.34 GiB (11.2%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: MZVLB512HAJQ-000L7 size: 476.94 GiB speed: 31.6 Gb/s lanes: 4 
           rotation: SSD serial: <filter> rev: 4L2QEXA7 scheme: MBR 
Partition: ID-1: / size: 19.56 GiB used: 17.2 GiB (87.9%) fs: ext4 dev: /dev/nvme0n1p1 
           ID-2: /home size: 440.89 GiB used: 36.14 GiB (8.2%) fs: ext4 dev: /dev/nvme0n1p3 
Swap:      ID-1: swap-1 type: partition size: 8 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/nvme0n1p2 
Sensors:   System Temperatures: cpu: 34.5 C mobo: N/A 
           Fan Speeds (RPM): cpu: 0 
Repos:     Packages: pacman: 732 
           Active pacman repo servers in: /etc/pacman.d/mirrorlist 
           1: http://ca.us.mirror.archlinux-br.org/$repo/os/$arch
Info:      Processes: 223 Uptime: 12m wakeups: 18 Memory: 15.17 GiB used: 1.82 GiB (12.0%) Init: systemd v: 248 Compilers: 
           gcc: 11.1.0 Shell: Bash v: 5.1.8 running-in: gnome-terminal inxi: 3.3.04 
```

**Comment by mtwebster** [comment]
Would you mind sharing the output of `w -h` ? We try to establish the tty of the graphical session and some other tty to pass to a backup screen if the screensaver crashes, but there could be some output from that command that I wasn't anticipating).

Thanks

**Comment by warwickmm** [comment]
`w -h` returns nothing:
```
$ w -h
$ 
```

**Comment by warwickmm** [comment]
I think I figured it out (sort of).  It turns out that with lxdm, `utmp` is not updated so `who` does not recognize my login session.  After switching to lightdm, `w -h` returns
```
$ w -h
ken      tty7      15:54    2:50   8.49s  0.54s cinnamon-session --session cinnamon
```
With lightdm and upgrading all the above-listed cinnamon packages, suspend now seems to be working without issues.

**Comment by warwickmm** [comment]
Thanks @mtwebster for the quick response!
