### ISSUE TITLE
Black screen when locked, no log in prompt present

### ISSUE THREAD

**Issue by n4turalZ0mbie** [linuxmint/cinnamon-screensaver#424]
```
 * Cinnamon-Screensaver version: 5.4.5+vanessa
 * Distribution: Cinnamon Mint 21 64 bit
 * Graphics hardware *and* driver used: VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (rev c5) (prog-if 00 [VGA controller])
 * Kernel driver in use: amdgpu
 * Kernel modules: amdgpu
 * Computer: Lenovo Yoga Slim 7 Pro 14ACH5
 * Monitor scale: 150 %
 * Resolution: 2240x1400@60
 ```

**Issue**
Black screen when locked, no log in prompt present.

**Steps to reproduce**
Ctrl+Alt+(lowercase) L or Click Lock Screen in the menu

**Expected behaviour**
The log in prompt should be present and I normally also see my background.

**Other information**
- The cursor is visible.
- I can unlock it by blindly entering my password.
- If I have display properties open (System Settings -> Display), with the little identifier visible in the top left corner, it works as expected.

I had issues before this update with fractional scaling. It was reset to 100 % when unlocked. The screen also flickered when locked, showing desktop content. I sometimes also temporarily lost menu items. I did not try to update the driver, I decided to wait for this official release. Those issues are fixed in this update, at least for me.

**Comment by ice10101** [comment]
I have exactly the same problem.

**Comment by hakostra** [comment]
I can confirm this issue on two different systems with Linux Mint 21.1

**Comment by budimanaa** [comment]
hi guys, any fix for this? I have the same problem but for me, I have to open any window to see the login screen (if there is no active/open window in my current workspace, the login screen goes blank with only the pointer visible)

**Comment by budimanaa** [comment]
@mtwebster hi there, the last command worked like a charm but as soon as I killed the process `CTRL + C` it would revert back.

``
cinnamon-screensaver --no-fallback --hold --debug
cinnamon-screensaver: no process found
Fractional scaling active: True
Trying to connect to logind...
Starting screensaver...
Debug mode active
Cinnamon Screensaver support not found in current theme - adding some...
service: 'GetActive' received, poking application.
org.gnome.ScreenSaver is gone from the session bus
org.mate.ScreenSaver is gone from the session bus
service: 'GetActive' received, poking application.
login client: found session path for user 'user' (session_id: c2): /org/freedesktop/login1/session/c2
Successfully using logind

``

**Comment by jonorthwash** [comment]
I'm getting this too, and my syslog fills with the following python traceback every time I restart `cinnamon-screensaver`.
```
2023-02-18T20:57:21.626221-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: Traceback (most recent call last):
2023-02-18T20:57:21.626317-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 767, in do_key_press_event
2023-02-18T20:57:21.626468-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.event_handler.on_key_press_event(event)
2023-02-18T20:57:21.626528-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 77, in on_key_press_event
2023-02-18T20:57:21.626577-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.manager.queue_dialog_key_event(event)
2023-02-18T20:57:21.626610-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/manager.py", line 469, in queue_dialog_key_event
2023-02-18T20:57:21.626678-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.stage.queue_dialog_key_event(event)
2023-02-18T20:57:21.626718-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 609, in queue_dialog_key_event
2023-02-18T20:57:21.626809-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.unlock_dialog.queue_key_event(event)
2023-02-18T20:57:21.626849-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: AttributeError: 'NoneType' object has no attribute 'queue_key_event'
2023-02-18T20:57:22.122712-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: Traceback (most recent call last):
2023-02-18T20:57:22.122940-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 767, in do_key_press_event
2023-02-18T20:57:22.123061-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.event_handler.on_key_press_event(event)
2023-02-18T20:57:22.123130-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 77, in on_key_press_event
2023-02-18T20:57:22.123163-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.manager.queue_dialog_key_event(event)
2023-02-18T20:57:22.123218-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/manager.py", line 469, in queue_dialog_key_event
2023-02-18T20:57:22.123260-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.stage.queue_dialog_key_event(event)
2023-02-18T20:57:22.123308-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 609, in queue_dialog_key_event
2023-02-18T20:57:22.123346-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.unlock_dialog.queue_key_event(event)
2023-02-18T20:57:22.123381-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: AttributeError: 'NoneType' object has no attribute 'queue_key_event'
2023-02-18T20:57:22.146643-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: Traceback (most recent call last):
2023-02-18T20:57:22.146777-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 767, in do_key_press_event
2023-02-18T20:57:22.146960-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.event_handler.on_key_press_event(event)
2023-02-18T20:57:22.147002-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 77, in on_key_press_event
2023-02-18T20:57:22.147049-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.manager.queue_dialog_key_event(event)
2023-02-18T20:57:22.147096-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/manager.py", line 469, in queue_dialog_key_event
2023-02-18T20:57:22.147159-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.stage.queue_dialog_key_event(event)
2023-02-18T20:57:22.147197-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 609, in queue_dialog_key_event
2023-02-18T20:57:22.147287-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.unlock_dialog.queue_key_event(event)
2023-02-18T20:57:22.147326-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: AttributeError: 'NoneType' object has no attribute 'queue_key_event'
```

**Comment by jonorthwash** [comment]
I also get a bunch of these:

```
2023-02-18T20:57:20.869986-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: Traceback (most recent call last):
2023-02-18T20:57:20.870082-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 761, in do_motion_notify_event
2023-02-18T20:57:20.870158-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.event_handler.on_motion_event(event)
2023-02-18T20:57:20.870206-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 51, in on_motion_event
2023-02-18T20:57:20.870241-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.on_user_activity()
2023-02-18T20:57:20.870278-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 32, in on_user_activity
2023-02-18T20:57:20.870333-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.manager.simulate_user_activity()
2023-02-18T20:57:20.870367-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/manager.py", line 181, in simulate_user_activity
2023-02-18T20:57:20.870451-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     if status.Locked and self.stage.initialize_pam():
2023-02-18T20:57:20.870524-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 668, in initialize_pam
2023-02-18T20:57:20.870637-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.unlock_dialog.initialize_auth_client()
2023-02-18T20:57:20.870676-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: AttributeError: 'NoneType' object has no attribute 'initialize_auth_client'
2023-02-18T20:57:20.877910-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: Traceback (most recent call last):
2023-02-18T20:57:20.878026-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 761, in do_motion_notify_event
2023-02-18T20:57:20.878189-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.event_handler.on_motion_event(event)
2023-02-18T20:57:20.878272-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 51, in on_motion_event
2023-02-18T20:57:20.878369-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.on_user_activity()
2023-02-18T20:57:20.878451-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 32, in on_user_activity
2023-02-18T20:57:20.878518-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.manager.simulate_user_activity()
2023-02-18T20:57:20.878550-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/manager.py", line 181, in simulate_user_activity
2023-02-18T20:57:20.878593-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     if status.Locked and self.stage.initialize_pam():
2023-02-18T20:57:20.878625-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 668, in initialize_pam
2023-02-18T20:57:20.878719-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.unlock_dialog.initialize_auth_client()
2023-02-18T20:57:20.878758-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: AttributeError: 'NoneType' object has no attribute 'initialize_auth_client'
```

**Comment by jonorthwash** [comment]
Hmm, it seems to start with this:
```
2023-02-18T20:57:18.940632-05:00 jangaq dbus-daemon[4709]: [session uid=1000 pid=4709] Activating service name='org.cinnamon.ScreenSaver' requested by ':1.779695' (uid=1000 pid=1825492 comm="/usr/bin/python3 /usr/bin/cinnamon-screensaver-com")
2023-02-18T20:57:19.018326-05:00 jangaq cinnamon-screen[1825501]: Failed to load module "xapp-gtk3-module"
2023-02-18T20:57:19.123387-05:00 jangaq dbus-daemon[4709]: [session uid=1000 pid=4709] Successfully activated service 'org.cinnamon.ScreenSaver'
2023-02-18T20:57:19.231116-05:00 jangaq cinnamon-session[4737]: WARNING: t+5218818.87545s: Detected that screensaver has appeared on the bus
2023-02-18T20:57:19.344992-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: Traceback (most recent call last):
2023-02-18T20:57:19.345146-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 278, in deactivate_after_timeout
2023-02-18T20:57:19.345304-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.manager.set_active(False)
2023-02-18T20:57:19.345364-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/manager.py", line 134, in set_active
2023-02-18T20:57:19.345474-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.despawn_stage()
2023-02-18T20:57:19.345522-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/manager.py", line 347, in despawn_stage
2023-02-18T20:57:19.345698-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.stage.cancel_unlocking()
2023-02-18T20:57:19.345748-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 712, in cancel_unlocking
2023-02-18T20:57:19.345994-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     utils.clear_clipboards(self.unlock_dialog)
2023-02-18T20:57:19.346048-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/utils.py", line 141, in clear_clipboards
2023-02-18T20:57:19.346155-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     clipboard = widget.get_clipboard(Gdk.SELECTION_PRIMARY)
2023-02-18T20:57:19.346264-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: AttributeError: 'NoneType' object has no attribute 'get_clipboard'
2023-02-18T20:57:19.357519-05:00 jangaq cs-backup-locke[1825520]: Failed to load module "xapp-gtk3-module"
2023-02-18T20:57:19.391224-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: Traceback (most recent call last):
2023-02-18T20:57:19.391306-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 761, in do_motion_notify_event
2023-02-18T20:57:19.391518-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.event_handler.on_motion_event(event)
2023-02-18T20:57:19.391571-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 51, in on_motion_event
2023-02-18T20:57:19.391616-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.on_user_activity()
2023-02-18T20:57:19.391650-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 32, in on_user_activity
2023-02-18T20:57:19.391680-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     self.manager.simulate_user_activity()
2023-02-18T20:57:19.391710-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/manager.py", line 181, in simulate_user_activity
2023-02-18T20:57:19.391748-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     if status.Locked and self.stage.initialize_pam():
2023-02-18T20:57:19.391779-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:   File "/usr/share/cinnamon-screensaver/stage.py", line 668, in initialize_pam
2023-02-18T20:57:19.391809-05:00 jangaq org.cinnamon.ScreenSaver[1825501]:     return self.unlock_dialog.initialize_auth_client()
2023-02-18T20:57:19.391848-05:00 jangaq org.cinnamon.ScreenSaver[1825501]: AttributeError: 'NoneType' object has no attribute 'initialize_auth_client'
```

**Comment by mtwebster** [comment]
@jonorthwash Is that version 5.4.5?

Can you try to reproduce this from the terminal as I described above?
https://github.com/linuxmint/cinnamon-screensaver/issues/424#issuecomment-1419219411

Thanks

**Comment by earthly-alien** [comment]
I have the same issue; cinnamon-screensaver v5.6.3, Linux Mint 21.1. It's somehow related to the fractional scaling option.

These are the tests I performed:

- Tests resulting in black lock screen, 100% reproducible (with Ctrl+Alt+L):
  - Fractional scaling on, set to 125%; all windows minimized
  - Fractional scaling on, set to 200%; all windows minimized
- Tests resulting in expected behavior (login field visible, etc.):
  - Fractional scaling on, set to 125%; at least one window visible on the desktop
  - Fractional scaling on, set to 125%; all windows minimized; running `cinnamon-screensaver --no-fallback --hold --debug`
  - Fractional scaling off, set to 100%
  - Fractional scaling off, set to 200%

**Comment by d-adamson** [comment]
I have the same issue on a 17 inch laptop.

**Zoom set to 100% -> wake up from suspend -> normal login  screen
Note the normal screen resolution below: AU Optronics res: 1920x1080**

`Graphics:
Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] vendor: Hewlett-Packard
driver: i915 v: kernel ports: active: eDP-1 empty: DP-1,HDMI-A-1,HDMI-A-2
bus-ID: 0000:00:02.0 chip-ID: 8086:9a49 class-ID: 0300
Device-2: Luxvisions Innotech HP TrueVision HD Camera type: USB
driver: uvcvideo bus-ID: 1-5:3 chip-ID: 30c9:002c class-ID: fe01
serial: <filter>
Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
unloaded: fbdev,vesa gpu: i915 display-ID: :0 screens: 1
Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x286mm (20.0x11.3")
s-diag: 583mm (23")
Monitor-1: eDP-1 model: AU Optronics res: 1920x1080 hz: 60 dpi: 128
size: 382x215mm (15.0x8.5") diag: 438mm (17.3") modes: 1920x1080
OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 22.2.5
direct render: Yes`

**Zoom set to 125% -> wake up from suspend -> black screen w pointer, but can blindly enter password
Note the strange screen resolution below: AU Optronics res: 3072x1728 hz:** 

`Graphics:
Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] vendor: Hewlett-Packard
driver: i915 v: kernel ports: active: eDP-1 empty: DP-1,HDMI-A-1,HDMI-A-2
bus-ID: 0000:00:02.0 chip-ID: 8086:9a49 class-ID: 0300
Device-2: Luxvisions Innotech HP TrueVision HD Camera type: USB
driver: uvcvideo bus-ID: 1-5:3 chip-ID: 30c9:002c class-ID: fe01
serial: <filter>
Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
unloaded: fbdev,vesa gpu: i915 display-ID: :0 screens: 1
Screen-1: 0 s-res: 3072x1728 s-dpi: 120 s-size: 650x366mm (25.6x14.4")
s-diag: 746mm (29.4")
Monitor-1: eDP-1 model: AU Optronics res: 3072x1728 hz: 60 dpi: 204
size: 382x215mm (15.0x8.5") diag: 438mm (17.3") modes: 1920x1080
OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 22.2.5
direct render: Yes`

**Comment by earthly-alien** [comment]
@d-adamson re: resolution. That's just how fractional scaling works - 1920 * 2 / 1.25 = 3072 px.

**Comment by kingsvijin** [comment]
same problem with me

**Comment by earthly-alien** [comment]
@mtwebster Just tested it and it doesn't seem to matter. The problem remains.

**Comment by edsml-hmc122** [comment]
I noticed that the black screen issue occurs any time that I have no windows focused (looking at just the Desktop -- doesn't matter if there are open apps minimised to the taskbar, or if I have no apps open at all). Then, either locking manually or locking by timeout causes the screen to be black when resuming. I'm using 150% fractional scaling, Linux Mint 21.1, on a 1920x1080 display.

**Comment by budimanaa** [comment]
@edsml-hmc122 did it happened in 100% scaling too?

**Comment by edsml-hmc122** [comment]
@budimanaa No, interestingly I only get this issue when the fractional scaling factor is not an integer, so 100% and 200% work fine, whereas 125%, 150%, and 175% give the black screen.

**Comment by jonorthwash** [comment]
@mtwebster:

> @jonorthwash Is that version 5.4.5?

Nope.  It's 5.4.4, which is the latest version my apparently very stale Debian mirror has in sid... (Okay, I'm gonna switch mirrors and upgrade now...)

> Can you try to reproduce this from the terminal as I described above? [#424 (comment)](https://github.com/linuxmint/cinnamon-screensaver/issues/424#issuecomment-1419219411)

This is the output I get: https://bpa.st/JHHAI

**Comment by jonorthwash** [comment]
> @mtwebster:
> 
> > @jonorthwash Is that version 5.4.5?
> 
> Nope. It's 5.4.4, which is the latest version my apparently very stale Debian mirror has in sid... (Okay, I'm gonna switch mirrors and upgrade now...)

Okay, I'm now on 5.6.3.  Similar issues.  At least I see a cursor now when it's locked, but still no login dialogue or anything else—just a background image.

> 
> > Can you try to reproduce this from the terminal as I described above? [#424 (comment)](https://github.com/linuxmint/cinnamon-screensaver/issues/424#issuecomment-1419219411)
> 
> This is the output I get: https://bpa.st/JHHAI

Now I get this traceback once on locking:

```
Traceback (most recent call last):
--
File "/usr/share/cinnamon-screensaver/stage.py", line 244, in deactivate_after_timeout
self.manager.set_active(False)
File "/usr/share/cinnamon-screensaver/manager.py", line 142, in set_active
self.despawn_stage()
File "/usr/share/cinnamon-screensaver/manager.py", line 358, in despawn_stage
self.stage.cancel_unlocking()
File "/usr/share/cinnamon-screensaver/stage.py", line 676, in cancel_unlocking
utils.clear_clipboards(self.unlock_dialog)
File "/usr/share/cinnamon-screensaver/util/utils.py", line 141, in clear_clipboards
clipboard = widget.get_clipboard(Gdk.SELECTION_PRIMARY)
^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_clipboard'
Problem setting up unlock dialog: invalid enum value: 10
Total failure somewhere, deactivating screensaver.
```

And then this a whole bunch:

```
Traceback (most recent call last):
File "/usr/share/cinnamon-screensaver/stage.py", line 725, in do_motion_notify_event
return self.event_handler.on_motion_event(event)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 51, in on_motion_event
self.on_user_activity()
File "/usr/share/cinnamon-screensaver/util/eventHandler.py", line 32, in on_user_activity
self.manager.simulate_user_activity()
File "/usr/share/cinnamon-screensaver/manager.py", line 189, in simulate_user_activity
if status.Locked and self.stage.initialize_pam():
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/cinnamon-screensaver/stage.py", line 632, in initialize_pam
return self.unlock_dialog.initialize_auth_client()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'initialize_auth_client'
```

The full output of `--debug` (etc.), minus a whole bunch of repeats of the second error, are at https://bpa.st/UF45Y

**Comment by bendover22** [comment]
2+ yrs after OP's bug report, same issue 
Using a desktop_1 monitor setup, LM 22, kernel 6.8.0-38; cinnamon-screensaver 6.2.1; cinnamon 6.2.9.
* Cinnamon-screensaver -Lock worked OK w/ previous Asus monitor, but **not w/** (v. similar) new Asus monitor.
* My solution was disable cinnamon-settings-daemon-screensaver-proxy.desktop, in sys. settings > Startup Applic.
Then install XscreenSaver 6.0.8.  Xscreensaver -  works fine w/ the new monitor.  

Had very similar prob w/ a modern (several yrs old) HP 1920 x 1080 monitor, (on laptop) in LM-**XFCE**.  Wouldn't wake, or took **10 - 15 min** to show locked screen login after key press).  

Tried 'fixes' for weeks (100's of _different_ ones on web).  Xscreensaver worked fine w/ the HP monitor.  
But an **OLD** Dell CRT monitor worked OK w/ the  XFCE screensaver that **didn't** work w/ HP monitor.
 
* Doesn't seem like "fractional scaling" (never used, here) is the only issue w/ cinnamon screensaver not unlocking.
* With **previous** monitor (1)  (desktop, 1- monitor), no probs w/ locked cinnamon-screensaver showing PW entry GUI if moved mouse or hit a key.

* NEW monitor(2)  (same desktop, same LM 22, 1-monitor), after screen lock & touching mouse / keyboard, it only flashed PW login screen for **2-4 seconds**, tops.  
* If clicked PW field before it blanked again, could blindly enter PW & unlock screen.  
If -didn't- click PW field fast, had to **power Off** / On monitor, to see GUI login - only 2-4 sec.

* On cinnamon-screensaver, cursor isn't pre-focused in PW field, but IS in Xscreensaver.

Tried using tty / CLI login (this screen also seemed to go black after few seconds) - it failed (?operator error).

(1) Old monitor - Asus **VS**229H-P  (mfg 2012) LED 1920 x 1080 used w/ both a discreet Nvidia GPU (HDMI) & w/ Intel IG (VGA).

(2) New monitor - Asus **VP**229Q (mfg nov 2024) LED 1920 x 1080.
Using **same:** OS & kernel; VGA; Intel IG; driver_ as  w/ previous Asus **VS**229 (that worked w/ cinnamon screensaver).
Can't test new monitor on the Nvidia GPU (ist kaput) .

**Comment by 10Gauge** [comment]
I noticed that if I CTRL-ALT-F1 then immediately CTRL-ALT-F7, I get the logon prompt back.
