### ISSUE TITLE
Can't switch users from lockscreen

### ISSUE THREAD

**Issue by mindtheegab** [linuxmint/cinnamon-screensaver#429]
```
 * Cinnamon version (cinnamon --version) 5.2.7-4: all
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds). no
 * Distribution - (ubuntu 22.04.)
 *  nvidia and mesa same result
 *64
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue
its impossible to login as a user while another user is logged in and locked the screen

### Steps to reproduce
log in with one user, lock the screen and click the users button

### Expected behaviour
i would expect to be able to change user but instead the button does nothing

**Comment by mtwebster** [comment]
Ubuntu maintainers will need to backport this or else you'll need to edit the file yourself.

@ItzSwirlz

**Comment by mindtheegab** [comment]
hi thanks for the quick answer i tried editing the file under /usr/share/cinnamon/screensaver but i get this now

```
```
itsupport@minion:~$ cinnamon-screensaver --debug                                                          
Traceback (most recent call last):
  File "/usr/bin/cinnamon-screensaver", line 18, in <module>
    from util import utils, settings
  File "/usr/share/cinnamon-screensaver/util/utils.py", line 106
    elif process_is_running("gdm3"):
IndentationError: unexpected indent
```


this is how that section looks like now

      app = Gio.AppInfo.create_from_commandline(command, "gdmflexiserver", 0)
        if app:
            app.launch(None, ctx)
             elif process_is_running("gdm3"):
        ctx = Gdk.Display.get_default().get_app_launch_context()

        app = Gio.AppInfo.create_from_commandline("gdmflexiserver", None, 0)
        if app:
            app.launch(None, ctx)
    elif os.getenv("XDG_SEAT_PATH") is not None:
        try:
            bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
            bus.call_sync("org.freedesktop.DisplayManager",
                          os.getenv("XDG_SEAT_PATH"),
                          "org.freedesktop.DisplayManager.Seat",
                          "SwitchToGreeter",
                          None,
                          None,
                          Gio.DBusCallFlags.NONE,
                          -1,
                          None)

        except GLib.Error as err:
            print("Switch user failed: " + err.message)
```

**Comment by mtwebster** [comment]
Indentation is critical in python - you may be better off just replacing the entire function:


```
def do_user_switch_timeout(data=None):
    if process_is_running("mdm"):
        command = "%s %s" % ("mdmflexiserver", "--startnew Standard")
        ctx = Gdk.Display.get_default().get_app_launch_context()

        app = Gio.AppInfo.create_from_commandline(command, "mdmflexiserver", 0)
        if app:
            app.launch(None, ctx)
    elif process_is_running("gdm"):
        command = "%s %s" % ("gdmflexiserver", "--startnew Standard")
        ctx = Gdk.Display.get_default().get_app_launch_context()

        app = Gio.AppInfo.create_from_commandline(command, "gdmflexiserver", 0)
        if app:
            app.launch(None, ctx)
    elif process_is_running("gdm3"):
        ctx = Gdk.Display.get_default().get_app_launch_context()

        app = Gio.AppInfo.create_from_commandline("gdmflexiserver", None, 0)
        if app:
            app.launch(None, ctx)
    elif os.getenv("XDG_SEAT_PATH") is not None:
        try:
            bus = Gio.bus_get_sync(Gio.BusType.SYSTEM, None)
            bus.call_sync("org.freedesktop.DisplayManager",
                          os.getenv("XDG_SEAT_PATH"),
                          "org.freedesktop.DisplayManager.Seat",
                          "SwitchToGreeter",
                          None,
                          None,
                          Gio.DBusCallFlags.NONE,
                          -1,
                          None)

        except GLib.Error as err:
            print("Switch user failed: " + err.message)
```

**Comment by mindtheegab** [comment]
thanks! works great now
